Factories = ["0xdD2bc74E7a5e613379663e72689e668300b42f37"]
#config
Action = "status" # buy, sell, approve, allowance, addliquidity, removeliquidity, status, check, mine
Pair = "any/ht" # any/bsc, usdt/bsc

[Mine]
TxMinAmount = 1.0 # 18 ANY
Reward = 2880
RewardToken = "ANY" # ANY
SellRewardToken = true
TxRate = 1.0
TxRewardPercent = 1.0
TxMinExpectPercent = 0.9 # 1: all
Rebase = "false"
StrategyReward = "percent" # percent/liquidity
StrategySycle = "blocktime"
Blocks_mine = [50, 60, 70, 80, 95]

[Exchange]
Amount_buy = 7045 # buy total per day with FSN
Amount_sell = 6013 # 0: follow Amount_buy, almost all sold as mach as buying
Times_mine_sycle = 5 # 0: use Height, others: rand
Height = 87 # mine block number, int
Sycles = 1 # mine Sycles, int. 0 for ever
Rounds = 2

[Sync]
BlockStart = 3260043
BlockEnd = 3260142
ScanAllExchange = false

[Transfer]
To = [""]

[[Contracts]]
Pair     = "ANY/HT"
Token    = "0x538cee985e930557d16c383783ca957fa90b63b3"
Exchange = "0x58ded31f93669eac7b18d4d19b0d122fa5e9263d"
[[Contracts]]
Pair     = "HTC/HT"
Token    = "0x734922E7b793B408cd434eEdAa407c9c0C575d1E" # HTC
Exchange = "0xae9b79172b6cd61f1e312b0bf05399f643111900" # HTc
[[Contracts]]
Pair     = "USDT/HT"
Token    = "0x0298c2b32eae4da002a15f36fdf7615bea3da047" # HUSD
Exchange = "0xe1eacc72830ae81668457bb2b3bd214dab9e3d0f" # HUSD

[Account]
Keystore = ""
Password = ""

[Blockchain]
GatewayURL = "https://http-mainnet.hecochain.com" # mainnet HT
GasLimit   = 8000000 # int
GasPrice   = 10000000000 # HT: int, wei
DeadLine   = 1800 # second

[Blocktime]
Blocks_day = 86400 # 24h * 60 * 60
Blocks_sycle = 1800 # 30m * 60
Block_start = 1607594400 # 20201210 18:00:00
AverageBlockTime = 3

[Blocknumber]
Blocks_day = 28800
Blocks_sycle = 60 # rewards sycle
Block_start = 756600
AverageBlockTime = 3

[Slipage]
Slipage = 0.05 #float

[Fee] # contract
Fee = 0.004 #float
